### ISSUE TITLE
Explanation of 5.1.0 "Removed thread safety in JasperCustomValues due to problems with memory leak"

### ISSUE THREAD

**Issue by stephanebarbey** [dynamicreports/dynamicreports#26]
Hi,

Thank you very much for taking over the maintenance of this project!

I have a question wrt. the changes vs 5.0.0 and 5.1.0, though. Change log says

- removed thread safety in JasperCustomValues due to problems with memory leak 

Does anyone remember, or could explain in a few words, what change was made? I am currently trying to find a memory leak with 5.0.0 that JasperCustomValues / JRVerticalFiller / JRFillSubReport, and, based on that note in the changelog,  wonder if the analysis had not already be done / a fix implemented?

Thanks,
-Stephane

**Comment by jan-moxter** [comment]
Hello, 
sorry I am not sure if we can help there.. we restarted DynamicReports with code based on 5.1.0. So its hard due to not being able to compare the versions. 

 Maybe @ghacupha does have an idea?

Jan

**Comment by enricog84** [comment]
I had this issue reported back then.
IIRC in `net.sf.dynamicreports.jasper.base.JasperCustomValues` the used `ThreadLocal` for `localJasperScriptlet` created the leak. I think the `net.sf.dynamicreports.jasper.base.JasperScriptlet` could not be cleaned up after being set in the ThreadLocal. As a quick and dirty workaround I tried to remove all ThreadLocal by using a method I found on [stackoverflow](https://stackoverflow.com/questions/3869026/how-to-clean-up-threadlocals/16644476#16644476) before every report creation.
But note, this may have side effects so you should probably not use it in production. The problem was sovled for me after upgrading to version 5.1.0. 

I posted a better description on the forums and sourceforge, but those are gone and I can't remember any more details. But maybe it helps. 

And if I have reason to post now, also from me a big thanks for taking over the project!

**Comment by ghacupha** [comment]
@sgrueter Just a thought : JasperCustomValues is a super container of values (custom types). This container has six different maps, indexed by strings, one of those maps has lists for DRIChartCustomizer, so no matter how you look at it, that's a pretty big object. The maps are also implemented in hashmaps (concurrent hashmaps don't exist in java 6, and the project version 4~5 was based-lined at java 6).
So if you have dozens of this object floating around in your RAM, and there are strong references to any number of objects referred to by the any of the 6 maps (80% chance that you do, you said "cache", right?), garbbage collection or not, not only will there be a leakage, but the CPU is overwhelmed as it is constantly calculating and comparing hashcodes from multiple layers of objects in these super containers. 
Just dozens of these is enough to bring the program down, and there's probably nothing GC can do. So, I might be tunnel-visioning here, but I was thinking a way  to resolve this may involve redesign in the library's api, to allow "JasperCustomValues", to be implemented, as an a thread-safe singleton, may be include something like a double-checked locking initializer. This unfortunately means that JasperCustomValues could only have one type of JasperScriptlet. Thoughts?

**Comment by sgrueter** [comment]
Hi Edwin

I finally found some time to think about your proposal and to dive into the rabbit hole of JasperCustomValues and JasperScriptlet.

First: the JasperCustomValues objects hold information specific to a report or sub dataset of a report. Therefore I think a singleton approach is not feasible.

Second: With "cache" I mean an instance of a fully compiled JasperReportBuilder containing the JasperCustomValues objects as well, so no leaking will happen. The cache is only used, because the report is too big and complex to compile it for every fill request, what would be the normal behavior of DynamicReports (and in this normal case no concurrency issues or memory leaks occur).
But if you use a cached report and fill it concurrently, then the "switching" of the JasperScriptlet instance in the JasperCosumValues by different threads causes problems and that's why I suggested to use ThreaLocal (but this in turn can lead to memory leaks of JasperScriptlets).

Now the best approach in my opinion would be, to use the JasperScriptlet directly to resolve values instead of delegating getValue() in JasperCustomValues to the current JasperScriptlet. I tried this by adjusting JasperCustomValues, JasperScriptlet, AbstractExpressionTransform and CrosstabTransform. But unfortunately this approach does not work if sub datasets are used, because in this case additional JasperCustomValues are introduced in DatasetTransform and some information used by the report is then spread over the different JasperCustomValues and can no longer be resolved by the JasperScriptlet.

So it looks like the usage of ThreadLocal is the only possibility to fill cached reports in a thread safe way. But maybe it would be possible to make this configurable by using a ScriptletFactory and two implementations of JasperScriptlet - a default one and one that uses ThreadLocal.

What do you think?

**Comment by sgrueter** [comment]
I think I found a simple solution: By using a JasperScriptletManager with two implementations in JasperCustomValues, a thread safe variant to manage the JasperScriptlet can be selected by setting a report property.
I could create a topic branch and a PR if you add me to the contributors.

**Comment by ghacupha** [comment]
Thanks @sgrueter I will be adding you to the contributor list shortly

**Comment by srbala** [comment]
@stephanebarbey @sgrueter please review and close this issie

**Comment by sgrueter** [comment]
Can be closed in my opinion: the current default is like in version 5.1.0 to prevent possible memory leaks and thread safety is normally not a problem. Thread safe rendering of **cached** reports can now be enabled by setting a report property (see #36).

**Comment by srbala** [comment]
@stephanebarbey @jan-moxter @ghacupha please close this issue
