### ISSUE TITLE
Is this Java 11 ready?

### ISSUE THREAD

**Issue by josepowera** [dynamicreports/dynamicreports#33]
We are moving from Java 8 to Java 11... Is this component ready and running in Java 11?

**Comment by ghacupha** [comment]
As it is, it has not been tested against java 11. It worked with java 9 however we are talking about the artefacts not the source code. As for the source code working with 9+ jdk requires certain profiles to be selected. This is despite the glaring absence of modules. So for now I would focus on getting those modules up and running, and then later trying it against jdk 10 and jdk 11, would be easy, since it's a matter of replacing the java EE modules (JAXB) that have been removed from the newer runtimes.

Now, the move to java 11 should have modules. It's an important part of this move. The only challenge I have is that the version we currently have for jasper reports does not seem to have modules. And this is not an issue until you declare your own modules, because because then you will run into issues with duplicate declarations in the dependencies for jasper reports. So it seems the maintainers are also "waiting for someone" to fix something. So I will keep checking their repositories for new snapshots. 

Another problem our code base itself has is type inference errors. Those were technically not considered errors in java 7 (which is the original baseline of this source code). They were merely malpractice, but correctly applied (as they were in this code base the original author), they enabled flexibility and ease of application. And being that this code is kind of huge, and to fix those inferences, one would have to reconfigure some generic declarations. If you don't break anything in the code itself, then you can be sure the client-facing API will have changed. That whole level of changes, would probably make the library less useful than more useful. Here options are to be weighed but we will utlimately get to java 11.

**Comment by ghacupha** [comment]
Update: I have tries installing jpms. This is a proper exercise in frustration, as it was evident that the dependencies were not ready. This project as it is, uses a lot of dependencies and that is becoming a problem, as one has to see hundreds of errors on split packages. To fix that we have to write scripts to smash artefacts together, or clone all those libraries and implement modules ourselves. I suggest total abandonment of the modules and focus on compatibility without modules.

Now, there is likely a bug in the jdk 9, that makes the animal sniffer detect "bad class files", that are supposedly not compatible with java 8. Ironically when you run the compilation with javac 8, this error does not come up, and the compilation will run just fine. This means the source code itself does not use java 9 api. This is an unfortunate problem as the jdk 9 is no longer supported by Oracle.

**Comment by ghacupha** [comment]
Newer Update: Openjdk 9 updated 181, reference implementation seems to run just fine without the animal sniffer detecting api issues. So i guess where jdk 9 is concerned stick with openjdk 9 update 181
