### ISSUE TITLE
ReportUtils.generateUniqueName(String) is not thread safe

### ISSUE THREAD

**Issue by sgrueter** [dynamicreports/dynamicreports#39]
## Expected Behavior
If multiple threads call ReportUtils.generateUniqueName(String) the generated names should be unique.

## Current Behavior
Since the postfix incrementor used (counter++) is not atomic, it is not guaranteed that the generated names are always unique when the method is called concurrently.

## Possible Solution
Make this method synchronized or use a lock (faster) to prevent concurrent access.

## Steps to Reproduce (for bugs)
Difficult to reproduce manually.
I will add a PR soon with a regression test to show how the bug can be triggered.

## Context
If an application using DynamicReports is run unter heavy load, this bug can lead to unexpected errors like "DRReportException: Value crosstabParametersExpression_28218_ not found".

## Your Environment
* Version used: 6.0.1-SNAPSHOT
* Java version being used: 1.8.0_171
* Operating System and version (desktop or mobile): MacOS Darwin Kernel Version 16.7.0 (desktop)

**Comment by ghacupha** [comment]
Hi @sgrueter ? Ok looks good since the tests have passed (our tests coverage are at around 75% percent, so that's with 75% confidence).  
So concurrence is still to me, one of the dark arts, so am just about 75% sure about this merger. You are right though, postfix incrementors are not atomic by nature, so it would be very easy to create duplicates by concurrence. I am going to merge it, and add that in the [changelog](https://github.com/dynamicreports/dynamicreports/blob/development/changelog.txt) as "Address of issue #39", so that in case something breaks, we can always come back to this and fix it, probably with an atomic [integer](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/atomic/AtomicInteger.html). Of course atomic integers and other such ideas will just increment complexity, so am really rooting for your solution. That cool? Nice catch by the way!

**Comment by sgrueter** [comment]
OK, thanks for merging Edwin.
