### ISSUE TITLE
Malware on website

### ISSUE THREAD

**Issue by Athas1980** [dynamicreports/dynamicreports#59]
Your issue may already be reported!
Please search on the [issue track](https://github.com/dynamicreports/dynamicreports/issues) before creating one.

## Expected Behavior
I should be able to go to the website that is linked from maven central without security issues

## Current Behavior
I am unable the website listed in firefox as it says dynamic reports is down.
## Possible Solution
If you no longer controll dynamicreports.com then change the url in pom.xml to point to this github repository.

## Context
I was checking some old dependencies we have in our project.  I tried to go to the website linked to see what the exact behaviour was.

**Comment by jan-moxter** [comment]
Thanks for this input. 
First of all:  **We do not have any controll over  www(point)dynamicreports(point)org or  www(point)dynamicreports(point)com** due to the reason that the originator of this project basically disappeared and we only try to keep the project alive. 

We will remove the current link and link to this project.
